**Write Linear Regression Model that can handle any size of features**

In [2]:
import numpy as np
import tensorflow as tf
import matplotlib.pyplot as plt

# Generate Dataset

In [3]:
def gensample(m,n):
  X = np.random.uniform(size = (m,n))
  C = np.random.uniform(size = (n))
  intercept = np.random.uniform()
  return X, X.dot(C) + intercept + np.random.normal(0, 0.1), C, intercept

In [4]:
number_of_sample = 500
number_of_train = number_of_sample - 50
dimensions = 10
X,Y,Theta,c = gensample(number_of_sample, dimensions)
X = X.astype('float32')
Y = Y.reshape(number_of_sample, 1)
X_train = X[:number_of_train,:]
y_train = Y[:number_of_train]
X_test = X[number_of_train:,]
y_test = Y[number_of_train:]

print('Theta : ', Theta)
print('C: ', c)

Theta :  [0.36879088 0.03020536 0.14768128 0.49663444 0.59847391 0.0326374
 0.97839361 0.14274178 0.55630263 0.97385446]
C:  0.48570646364453507


# Build Model

In [53]:
class LinearRegression(tf.Module):
  def __init__(self, features, name=None):
    '''
      features: the number of features
    '''
    super().__init__(name=name)
    #Define variables here.
    self.theta = tf.Variable(np.random.uniform([features,1]),name ='theta')
    self.intercept = tf.Variable(np.random.uniform([1]),name = 'intercept')

  def __call__(self,x):
    '''
      x : matrix of size m x d, where m is the number of samples 
          and d is the number of features.
    '''
    # Write the code for calculate Theta * x
    return tf.matmul(x,self.theta)+self.intercept

# Define Loss Function

In [54]:
def loss(target, predicted):
  '''
    target : y_true
    predicted : y_predict
  '''
  return  tf.reduce_mean(tf.square(target - predicted))

# Trainging Loop

In [55]:
def train(model, x, y_true, learning_rate = 0.1):
  '''
    model : your linear regression model
    x : input
    y_true : target output
    learning_rate : learning rate for SGD
  '''
  with tf.GradientTape() as tape:
    y_predicted = model(x)
    current_loss = loss(y_true, y_predicted)
  
  # Coding your SGD here
  #d_theta, d_intercept = tape.gradient(current_loss, ...)
    d_theta, d_intercept = tape.gradient(current_loss,[model.theta,model.intercept])
  #model.theta.assign_sub(...)
    model.theta.assign_sub(learning_rate * d_theta)
    model.intercept.assign_sub(learning_rate * d_intercept)


In [56]:
def training_loop(model, x, y, epochs, alpha):
  for epoch in range(1, epochs+1):
    train(model, x, y, learning_rate = alpha)

# Training Samples

In [57]:
# Create model and train the model.
#model = LinearRegression(10)
model = LinearRegression(10)

In [58]:
#training_loop(model, X_train, y_train , ..., ....)
training_loop(model, X_train, y_train , 100, 0.01)

InvalidArgumentError: cannot compute MatMul as input #1(zero-based) was expected to be a float tensor but is a double tensor [Op:MatMul]

# Testing Model

In [10]:
# Print the results of your model. Then, compare with actual y.
#y_predicted = model(X_train)
y_predicted = model(X_train)
#print(y_train)
#print(y_predicted)
print(y_train)



NameError: name 'model' is not defined

In [15]:
print(y_predicted)

tf.Tensor(
[[2.6605597 2.69879   2.3922935 ... 2.4259183 2.5622234 2.4903727]
 [2.3846784 2.6848664 2.6259465 ... 2.5804543 2.4519384 2.36767  ]
 [2.6231632 2.4475584 2.6241708 ... 2.6142526 2.3262067 2.5467746]
 ...
 [2.534937  2.72882   2.413994  ... 2.4773135 2.6831017 2.4371302]
 [2.439256  2.3608885 2.3272295 ... 2.5745668 2.4938896 2.6026266]
 [2.4404016 2.4515898 2.6178358 ... 2.6282494 2.413891  2.5173383]], shape=(450, 10), dtype=float32)
