In [9]:
import numpy as np
import tensorflow as tf
import matplotlib.pyplot as plt

In [10]:
x_data = np.array(
    [[1, 2, 1, 1],
     [2, 1, 3, 2],
     [3, 1, 3, 4],
     [4, 1, 5, 5],
     [1, 7, 5, 5],
     [1, 2, 5, 6],
     [1, 6, 6, 6],
     [1, 7, 7, 7]], dtype=np.float32)

y_data = np.array(
    [[0, 0, 1],
     [0, 0, 1],
     [0, 0, 1],
     [0, 1, 0],
     [0, 1, 0],
     [0, 1, 0],
     [1, 0, 0],
     [1, 0, 0]], dtype=np.float32
)

$\theta_{11} x_1 + \theta_{12} x_2 + \theta_{13} x_3 + \theta_{14} x_4 + \theta_{10}$ 

$\theta_{21} x_1 + \theta_{22} x_2 + \theta_{23} x_3 + \theta_{24} x_4 + \theta_{20}$ 

$\theta_{31} x_1 + \theta_{32} x_2 + \theta_{33} x_3 + \theta_{34} x_4 + \theta_{30}$ 

$\begin{bmatrix}
\theta_{11} & \theta_{12} & \theta_{13} & \theta_{14}\\ 
\theta_{21} & \theta_{22} & \theta_{23} & \theta_{24}\\ 
\theta_{31} & \theta_{32} & \theta_{33} & \theta_{34}\\ 
\end{bmatrix}
\begin{bmatrix}
x_1\\x_2\\x_3\\x_4
\end{bmatrix} + 
\begin{bmatrix}
\theta_{10}\\\theta_{20}\\\theta_{30}
\end{bmatrix}$

In [42]:
class SoftmaxRegression(tf.Module):
  def __init__(self, num_features, num_classes, name=None):
    super().__init__(name=name)
    self.W = tf.Variable(tf.random.normal((num_features, num_classes)), name='weight')
    self.b = tf.Variable(tf.random.normal((num_classes, )), name='bias')

  def __call__(self,X):
    return tf.nn.softmax(tf.matmul(X, self.W) + self.b)

In [43]:
def loss(y_true, y_predicted):
  cost = -tf.reduce_sum(y_true*tf.math.log(y_predicted), axis = 1)
  return tf.reduce_mean(cost)

In [44]:
def train(model, x, y, learning_rate = 0.1):
  with tf.GradientTape() as tape:
    current_loss = loss(y, model(x))
  
  d_W, d_b = tape.gradient(current_loss, [model.W, model.b])

  model.W.assign_sub(learning_rate * d_W)
  model.b.assign_sub(learning_rate * d_b)

In [45]:
def training_loop(model, x, y, epochs, alpha):
  for epoch in range(1, epochs+1):
    train(model, x, y, learning_rate = alpha)

In [49]:
model = SoftmaxRegression(4,3)
training_loop(model, x_data, y_data , 2000, 0.01)

In [50]:
b = model(x_data)

In [51]:
tf.argmax(b,1), tf.argmax(y_data,1)

(<tf.Tensor: shape=(8,), dtype=int64, numpy=array([2, 2, 2, 1, 0, 1, 0, 0])>,
 <tf.Tensor: shape=(8,), dtype=int64, numpy=array([2, 2, 2, 1, 1, 1, 0, 0])>)

In [41]:
b

<tf.Tensor: shape=(8, 3), dtype=float32, numpy=
array([[3.5789800e-03, 2.9328369e-02, 9.6709263e-01],
       [1.4182037e-02, 1.8982348e-01, 7.9599440e-01],
       [4.8760884e-04, 3.5054079e-01, 6.4897156e-01],
       [6.0381991e-04, 6.6837060e-01, 3.3102560e-01],
       [5.0687671e-01, 4.5808718e-01, 3.5036132e-02],
       [2.5727865e-01, 7.4240243e-01, 3.1885519e-04],
       [6.2630546e-01, 3.7252137e-01, 1.1731860e-03],
       [7.4180710e-01, 2.5804475e-01, 1.4808583e-04]], dtype=float32)>